before:
  hooks:
    - go mod tidy
builds:
- env:
  - CGO_ENABLED=0
archives:
checksum:
  name_template: 'checksums.txt'
release:
  name_template: "{{.ProjectName}}-v{{.Version}}"
brew:
  github:
    owner: nextdns
    name: homebrew-tap
  commit_author:
    name: NextDNS Team
    email: team@nextdns.io
  homepage: https://nextdns.io
  description: NextDNS DNS/53 to DoH Proxy
nfpms:
  -
    id: deb
    vendor: NextDNS Inc
    homepage: https://nextdns.io
    maintainer: NextDNS Team <team@nextdns.io>
    description: NextDNS DNS/53 to DoH Proxy
    license: MIT
    formats: [deb]
    bindir: /usr/bin
  -
    id: rpm
    vendor: NextDNS Inc
    homepage: https://nextdns.io
    maintainer: NextDNS Team <team@nextdns.io>
    description: NextDNS DNS/53 to DoH Proxy
    license: MIT
    formats: [rpm]
    bindir: /usr/bin
puts:
  - 
    name: deb
    ids: [deb]
    mode: archive
    target: https://api.bintray.com/content/nextdns/deb/{{.ProjectName}}/{{.Version}}/pool/main/m/
    username: nextdns
  - 
    name: rpm
    ids: [rpm]
    mode: archive
    target: https://api.bintray.com/content/nextdns/rpm/{{.ProjectName}}/{{.Version}}/
    username: nextdns
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
