before:
  hooks:
    - go mod tidy
builds:
- 
  goos:
  - freebsd
  - netbsd
  - openbsd
  - dragonfly
  - linux
  - darwin
  - windows
  goarch:
  - 386
  - amd64
  - arm
  - arm64
  - mips
  - mipsle
  - mips64
  - mips64le
  goarm:
  - 5
  - 6
  - 7
  gomips:
  - softfloat
  - hardfloat
  env:
  - CGO_ENABLED=0
archives:
-
  format_overrides:
  -
    goos: windows
    format: zip
  files:
  - LICENSE
  - README.md
checksum:
  name_template: 'checksums.txt'
release:
  name_template: "{{.ProjectName}}-v{{.Version}}"
brews:
-
  github:
    owner: nextdns
    name: homebrew-tap
  commit_author:
    name: NextDNS Team
    email: team@nextdns.io
  homepage: https://nextdns.io
  description: NextDNS DNS/53 to DoH Proxy
  caveats: "To install NextDNS, run the following command:

    sudo nextdns install --config <your_conf_id>

Then setup your DNS manually to 127.0.0.1 or by running:

    sudo nextdns activate
"
nfpms:
  -
    id: deb
    vendor: NextDNS Inc
    homepage: https://nextdns.io
    maintainer: NextDNS Team <team@nextdns.io>
    description: NextDNS DNS/53 to DoH Proxy
    license: MIT
    formats: [deb]
    bindir: /usr/bin
    scripts:
      postinstall: ".goreleaser/postinstall.sh"
      preremove: ".goreleaser/preremove_deb.sh"
  -
    id: rpm
    vendor: NextDNS Inc
    homepage: https://nextdns.io
    maintainer: NextDNS Team <team@nextdns.io>
    description: NextDNS DNS/53 to DoH Proxy
    license: MIT
    formats: [rpm]
    bindir: /usr/bin
    scripts:
      postinstall: ".goreleaser/postinstall.sh"
      preremove: ".goreleaser/preremove_rpm.sh"
dockers:
  -
    image_templates:
    - "nextdns/nextdns:latest"
    - "nextdns/nextdns:{{ .Tag }}"
    dockerfile: .goreleaser/Dockerfile
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.name={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
